"""add_callback_scheduling_fields

Revision ID: 9d7b28532bf6
Revises: 5fa8207135ad
Create Date: 2025-12-24 20:31:02.383342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d7b28532bf6'
down_revision: Union[str, Sequence[str], None] = '5fa8207135ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Enum('WRONG_NUMBER', 'DO_NOT_CALL', 'FRAUD', 'SPAM', 'DUPLICATE', 'OTHER', name='blacklistreason'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacklist_id'), 'blacklist', ['id'], unique=False)
    op.create_index(op.f('ix_blacklist_phone'), 'blacklist', ['phone'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('couriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('base_rate', sa.Float(), nullable=True),
    sa.Column('cod_fee_percent', sa.Float(), nullable=True),
    sa.Column('total_shipments', sa.Integer(), nullable=True),
    sa.Column('delivered_count', sa.Integer(), nullable=True),
    sa.Column('returned_count', sa.Integer(), nullable=True),
    sa.Column('avg_delivery_days', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_couriers_id'), 'couriers', ['id'], unique=False)
    op.create_table('bordereaux',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bordereau_number', sa.String(length=20), nullable=True),
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('total_cod_amount', sa.Float(), nullable=True),
    sa.Column('total_shipping', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('pickup_date', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bordereaux_bordereau_number'), 'bordereaux', ['bordereau_number'], unique=True)
    op.create_index(op.f('ix_bordereaux_id'), 'bordereaux', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('selling_price', sa.Float(), nullable=False),
    sa.Column('compare_at_price', sa.Float(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('track_inventory', sa.Boolean(), nullable=True),
    sa.Column('allow_backorder', sa.Boolean(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('dimensions', sa.String(length=100), nullable=True),
    sa.Column('variants', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('gallery_images', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('call_script', sa.Text(), nullable=True),
    sa.Column('confirmation_script', sa.Text(), nullable=True),
    sa.Column('total_sold', sa.Integer(), nullable=True),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('call_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('callback_scheduled', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_notes_id'), 'call_notes', ['id'], unique=False)
    op.create_index(op.f('ix_call_notes_lead_id'), 'call_notes', ['lead_id'], unique=False)
    op.create_table('lead_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('note_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lead_note_lead_created', 'lead_notes', ['lead_id', 'created_at'], unique=False)
    op.create_index('idx_lead_note_type', 'lead_notes', ['note_type'], unique=False)
    op.create_index('idx_lead_note_user_created', 'lead_notes', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_lead_notes_created_at'), 'lead_notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_lead_notes_id'), 'lead_notes', ['id'], unique=False)
    op.create_index(op.f('ix_lead_notes_lead_id'), 'lead_notes', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_notes_note_type'), 'lead_notes', ['note_type'], unique=False)
    op.create_index(op.f('ix_lead_notes_user_id'), 'lead_notes', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('delivery_charges', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'PROCESSING', 'SHIPPED', 'OUT_FOR_DELIVERY', 'DELIVERED', 'FAILED', 'RETURNED', 'REFUNDED', name='orderstatus'), nullable=True),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('confirmed_by', sa.String(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('courier', sa.String(length=50), nullable=True),
    sa.Column('courier_tracking_url', sa.String(length=500), nullable=True),
    sa.Column('tracking_number', sa.String(), nullable=True),
    sa.Column('delivery_partner', sa.String(), nullable=True),
    sa.Column('delivery_attempts', sa.Integer(), nullable=True),
    sa.Column('last_delivery_attempt', sa.DateTime(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('out_for_delivery_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_failed', sa.Boolean(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('payment_collected', sa.Boolean(), nullable=True),
    sa.Column('payment_collected_at', sa.DateTime(), nullable=True),
    sa.Column('cash_collected', sa.Float(), nullable=True),
    sa.Column('is_returned', sa.Boolean(), nullable=True),
    sa.Column('return_reason', sa.Text(), nullable=True),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('variant_name', sa.String(length=200), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('capacity', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('price_override', sa.Float(), nullable=True),
    sa.Column('cost_override', sa.Float(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variants_id'), 'product_variants', ['id'], unique=False)
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=True)
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('previous_stock', sa.Integer(), nullable=False),
    sa.Column('new_stock', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cost_per_unit', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_id'), 'stock_movements', ['id'], unique=False)
    op.create_table('order_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('old_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_history_id'), 'order_history', ['id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_sku', sa.String(length=100), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_number', sa.String(length=50), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('bordereau_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('customer_city', sa.String(length=50), nullable=True),
    sa.Column('customer_address', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('package_count', sa.Integer(), nullable=True),
    sa.Column('cod_amount', sa.Float(), nullable=True),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('collected_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('status_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_attempts', sa.Integer(), nullable=True),
    sa.Column('last_attempt_date', sa.DateTime(), nullable=True),
    sa.Column('last_attempt_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bordereau_id'], ['bordereaux.id'], ),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_id'), 'shipments', ['id'], unique=False)
    op.create_index(op.f('ix_shipments_tracking_number'), 'shipments', ['tracking_number'], unique=True)
    op.create_table('shipment_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_tracking_id'), 'shipment_tracking', ['id'], unique=False)
    op.add_column('leads', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('leads', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('phone', sa.String(length=20), nullable=False))
    op.add_column('leads', sa.Column('alternate_phone', sa.String(length=20), nullable=True))
    op.add_column('leads', sa.Column('company', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('product_interest', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('unit_price', sa.Float(), nullable=True))
    op.add_column('leads', sa.Column('total_amount', sa.Float(), nullable=True))
    op.add_column('leads', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('lead_score', sa.Integer(), nullable=False))
    op.add_column('leads', sa.Column('conversion_probability', sa.Float(), nullable=False))
    op.add_column('leads', sa.Column('last_contact_date', sa.DateTime(), nullable=True))
    op.add_column('leads', sa.Column('last_call_date', sa.DateTime(), nullable=True))
    op.add_column('leads', sa.Column('next_follow_up', sa.DateTime(), nullable=True))
    op.add_column('leads', sa.Column('call_attempts', sa.Integer(), nullable=False))
    op.add_column('leads', sa.Column('callback_time', sa.DateTime(), nullable=True))
    op.add_column('leads', sa.Column('callback_notes', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('callback_assigned_to', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('callback_completed', sa.Boolean(), nullable=True))
    op.add_column('leads', sa.Column('callback_reminder_sent', sa.Boolean(), nullable=True))
    op.add_column('leads', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    op.alter_column('leads', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('leads', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('leads', 'source',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('WEBSITE', 'FACEBOOK', 'INSTAGRAM', 'WHATSAPP', 'TIKTOK', 'REFERRAL', 'OTHER', name='leadsource'),
               nullable=False)
    op.alter_column('leads', 'status',
               existing_type=postgresql.ENUM('NEW', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'RETURNED', name='lead_status_enum'),
               type_=sa.Enum('NEW', 'CONTACTED', 'QUALIFIED', 'CONFIRMED', 'PROPOSAL', 'NEGOTIATION', 'WON', 'LOST', 'CALLBACK', 'NO_ANSWER', 'BUSY', 'NOT_INTERESTED', 'INTERESTED', 'CANCELLED', 'WRONG_NUMBER', name='leadstatus'),
               existing_nullable=False)
    op.alter_column('leads', 'notes',
               existing_type=sa.TEXT(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_index(op.f('ix_leads_city'), table_name='leads')
    op.drop_index(op.f('ix_leads_customer_phone'), table_name='leads')
    op.create_index('idx_lead_assigned_score', 'leads', ['assigned_to', 'lead_score'], unique=False)
    op.create_index('idx_lead_score_status', 'leads', ['lead_score', 'status'], unique=False)
    op.create_index('idx_lead_status_created', 'leads', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_leads_assigned_to'), 'leads', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_leads_lead_score'), 'leads', ['lead_score'], unique=False)
    op.create_foreign_key(None, 'leads', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'leads', 'users', ['callback_assigned_to'], ['id'], ondelete='SET NULL')
    op.drop_column('leads', 'product_name')
    op.drop_column('leads', 'shipped_at')
    op.drop_column('leads', 'customer_email')
    op.drop_column('leads', 'amount')
    op.drop_column('leads', 'delivered_at')
    op.drop_column('leads', 'customer_phone')
    op.drop_column('leads', 'confirmed_at')
    op.drop_column('leads', 'customer_name')
    op.drop_column('leads', 'product_description')
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('leads_assigned', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('leads_converted', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('calls_made', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('orders_created', sa.Integer(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'CALL_CENTER', 'FULFILLMENT', 'MARKETING', name='userrole'),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.alter_column('users', 'last_login',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('ADMIN', 'CALL_CENTER', 'FULFILLMENT', 'MARKETING', name='userrole'),
               nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('users', 'orders_created')
    op.drop_column('users', 'calls_made')
    op.drop_column('users', 'leads_converted')
    op.drop_column('users', 'leads_assigned')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'username')
    op.add_column('leads', sa.Column('product_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('customer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('leads', sa.Column('confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('customer_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('leads', sa.Column('delivered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('leads', sa.Column('customer_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('shipped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('product_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index(op.f('ix_leads_lead_score'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_to'), table_name='leads')
    op.drop_index('idx_lead_status_created', table_name='leads')
    op.drop_index('idx_lead_score_status', table_name='leads')
    op.drop_index('idx_lead_assigned_score', table_name='leads')
    op.create_index(op.f('ix_leads_customer_phone'), 'leads', ['customer_phone'], unique=False)
    op.create_index(op.f('ix_leads_city'), 'leads', ['city'], unique=False)
    op.alter_column('leads', 'notes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('leads', 'status',
               existing_type=sa.Enum('NEW', 'CONTACTED', 'QUALIFIED', 'CONFIRMED', 'PROPOSAL', 'NEGOTIATION', 'WON', 'LOST', 'CALLBACK', 'NO_ANSWER', 'BUSY', 'NOT_INTERESTED', 'INTERESTED', 'CANCELLED', 'WRONG_NUMBER', name='leadstatus'),
               type_=postgresql.ENUM('NEW', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'RETURNED', name='lead_status_enum'),
               existing_nullable=False)
    op.alter_column('leads', 'source',
               existing_type=sa.Enum('WEBSITE', 'FACEBOOK', 'INSTAGRAM', 'WHATSAPP', 'TIKTOK', 'REFERRAL', 'OTHER', name='leadsource'),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('leads', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('leads', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('leads', 'tags')
    op.drop_column('leads', 'callback_reminder_sent')
    op.drop_column('leads', 'callback_completed')
    op.drop_column('leads', 'callback_assigned_to')
    op.drop_column('leads', 'callback_notes')
    op.drop_column('leads', 'callback_time')
    op.drop_column('leads', 'call_attempts')
    op.drop_column('leads', 'next_follow_up')
    op.drop_column('leads', 'last_call_date')
    op.drop_column('leads', 'last_contact_date')
    op.drop_column('leads', 'conversion_probability')
    op.drop_column('leads', 'lead_score')
    op.drop_column('leads', 'assigned_to')
    op.drop_column('leads', 'total_amount')
    op.drop_column('leads', 'unit_price')
    op.drop_column('leads', 'quantity')
    op.drop_column('leads', 'product_interest')
    op.drop_column('leads', 'company')
    op.drop_column('leads', 'alternate_phone')
    op.drop_column('leads', 'phone')
    op.drop_column('leads', 'email')
    op.drop_column('leads', 'last_name')
    op.drop_column('leads', 'first_name')
    op.drop_index(op.f('ix_shipment_tracking_id'), table_name='shipment_tracking')
    op.drop_table('shipment_tracking')
    op.drop_index(op.f('ix_shipments_tracking_number'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_order_history_id'), table_name='order_history')
    op.drop_table('order_history')
    op.drop_index(op.f('ix_stock_movements_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_lead_notes_user_id'), table_name='lead_notes')
    op.drop_index(op.f('ix_lead_notes_note_type'), table_name='lead_notes')
    op.drop_index(op.f('ix_lead_notes_lead_id'), table_name='lead_notes')
    op.drop_index(op.f('ix_lead_notes_id'), table_name='lead_notes')
    op.drop_index(op.f('ix_lead_notes_created_at'), table_name='lead_notes')
    op.drop_index('idx_lead_note_user_created', table_name='lead_notes')
    op.drop_index('idx_lead_note_type', table_name='lead_notes')
    op.drop_index('idx_lead_note_lead_created', table_name='lead_notes')
    op.drop_table('lead_notes')
    op.drop_index(op.f('ix_call_notes_lead_id'), table_name='call_notes')
    op.drop_index(op.f('ix_call_notes_id'), table_name='call_notes')
    op.drop_table('call_notes')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_bordereaux_id'), table_name='bordereaux')
    op.drop_index(op.f('ix_bordereaux_bordereau_number'), table_name='bordereaux')
    op.drop_table('bordereaux')
    op.drop_index(op.f('ix_couriers_id'), table_name='couriers')
    op.drop_table('couriers')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_blacklist_phone'), table_name='blacklist')
    op.drop_index(op.f('ix_blacklist_id'), table_name='blacklist')
    op.drop_table('blacklist')
    # ### end Alembic commands ###
